### ISSUE TITLE
Bower not installing latest version

### ISSUE THREAD

**Issue by simonasdev** [bendrucker/angular-sockjs#4]
Hey @bendrucker, I had to run `bower install angular-sockjs#v0.1` to actually install the latest version. Could you name the following versions tags only with numbers, without the 'v' prefix ('0.1' in this case), so bower could resolve the latest version automatically? (As of now, 0.0.1 is resolved as the latest version)

**Comment by bendrucker** [comment]
Nope, can't do that. I think Bower supports a prefix and the problem is that one has a prefix and one doesn't: https://github.com/bower/bower/issues/1069. Just deleted the 0.0.1 tag, hopefully that fixes it.

**Comment by simonasdev** [comment]
It did fix it. Thanks!
